### ISSUE TITLE
Start action is not called

### ISSUE THREAD

**Issue by florianislitzer** [dgerod/rosplan_interface#11] opened 2019-10-13 18:08 UTC
Hi im trying to use your action interface with the SimpleAction class.

![image](https://user-images.githubusercontent.com/25135477/66719822-e4ec3800-edf4-11e9-8711-46266131d37c.png)

I have overridden the start function according to your example, unfortunatly the function is never called and i get this warnings:
![image](https://user-images.githubusercontent.com/25135477/66719847-1a912100-edf5-11e9-8aeb-e2144adc6a19.png)

Do you see any obvious error here or do you have any hint to find the error?

By the way - thanks for your work, would make life way easier!

**Comment by dgerod** [comment] 2019-10-26 06:24
Sorry for my late answer but I was traveling. 

Doing a quick check I have just found the problem, there is a mistake in the examples. **The problem is that README information is incorrect**, it is written that you have to overwrite "start()" method of the action but it should be "_start(). Some time ago I changed this method is protected as it is called internally by "SimpleAction" class, but I forgot to update the README.

Therefore, when you do what it is written in the examples the "execute()" method of "SimpleAction" class in "action_interface.py" file is not able to find "_start()" as "start()" was defined instead. 

And thanks to your issue I have also found a related issue in "planner_simple_action decorator" :-), this decorator was adding "start()" method as explained in examples instead "_start()" as it should. 

I have fixed all, so, please, **review PR #13, try if current code works and close the issue**. Thanks!

**Closed as completed** 2019-11-27 05:34 UTC
Labels: defect
